name = "Euterpe"
uuid = "edad34ee-b7ef-4ff5-97e3-e3388d3c4868"
authors = ["Avik Sengupta <avik@sengupta.net> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
